/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    pricing: Pricing;
    promotions: Promotion;
    services: Service;
    'team-members': TeamMember;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en' | 'uk') | ('es' | 'en' | 'uk')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'header-footer': HeaderFooter;
    'site-contacts': SiteContact;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'header-footer': HeaderFooterSelect<false> | HeaderFooterSelect<true>;
    'site-contacts': SiteContactsSelect<false> | SiteContactsSelect<true>;
  };
  locale: 'es' | 'en' | 'uk';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use home for the homepage or a URL path like about-us
   */
  slug: string;
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            sectionTitle?: string | null;
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            itemLayout?: ('column' | 'row') | null;
            items: {
              icon?: (number | null) | Media;
              title: string;
              /**
               * Supports bold, italic and underline formatting.
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages';
          }
        | {
            sectionTitle?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            /**
             * Frontend can alternate image and text automatically by order.
             */
            items: {
              title?: string | null;
              /**
               * Supports bold, italic and underline formatting.
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              buttonText?: string | null;
              buttonLink?: string | null;
              image: number | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutUsGrid';
          }
        | {
            sectionTitle?: string | null;
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            itemLayout?: ('column' | 'row') | null;
            items: {
              icon?: (number | null) | Media;
              title: string;
              /**
               * Supports bold, italic and underline formatting.
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'philosophy';
          }
        | {
            position?: ('left' | 'right') | null;
            promotion: number | Promotion;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promotions';
          }
        | {
            position?: ('left' | 'right') | null;
            title?: string | null;
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            images: {
              image: number | Media;
              id?: string | null;
            }[];
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            sectionTitle?: string | null;
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            source?: ('all' | 'manual') | null;
            selectedMembers?: (number | TeamMember)[] | null;
            sliderLimit?: number | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            sectionTitle?: string | null;
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            /**
             * Paste the review widget code or placeholder markup.
             */
            embedCode?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews';
          }
        | {
            position?: ('left' | 'right') | null;
            title?: string | null;
            /**
             * Supports bold, italic and underline formatting.
             */
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            buttonText?: string | null;
            buttonLink?: string | null;
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentImage';
          }
        | {
            position?: ('left' | 'right') | null;
            image: number | Media;
            pricingGroup: number | Pricing;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingGroupShowcase';
          }
        | {
            title?: string | null;
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            /**
             * Supports bold, italic and underline formatting.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Optional background image for this centered text block.
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Hex color for the overlay that sits on top of the background image.
             */
            overlayColor?: string | null;
            /**
             * 0 means fully transparent, 100 means fully opaque.
             */
            overlayOpacity?: number | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'globalContactSection';
          }
        | {
            sectionTitle?: string | null;
            /**
             * Use smaller vertical padding when the block has only a title or a short intro.
             */
            compactSpacing?: boolean | null;
            sectionDescription?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            formTitle?: string | null;
            formDescription?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            submitButtonLabel?: string | null;
            fullNamePlaceholder?: string | null;
            phonePlaceholder?: string | null;
            emailPlaceholder?: string | null;
            patientTypePlaceholder?: string | null;
            patientTypeOptions?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            referralSourcePlaceholder?: string | null;
            referralSourceOptions?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            commentPlaceholder?: string | null;
            successMessage?: string | null;
            errorMessage?: string | null;
            /**
             * Reorder rows shown in the left contact column.
             */
            contactRowsOrder?:
              | {
                  row: 'email' | 'phone' | 'address' | 'transport' | 'social';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSection';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  validUntil: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  position: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo: number | Media;
  photoHover?: (number | null) | Media;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items?:
    | {
        serviceName: string;
        price: string;
        /**
         * Optional. For example: from
         */
        pricePrefix?: string | null;
        note?: string | null;
        /**
         * Optional. Link this pricing row to a detailed service page.
         */
        servicePage?: (number | null) | Service;
        id?: string | null;
      }[]
    | null;
  detailsLinkLabel?: string | null;
  /**
   * Додайте сюди категорії, наприклад "Діагностика та профілактика" або "Хірургія"
   */
  categories?:
    | {
        categoryTitle: string;
        /**
         * Наприклад: "Цей напрям вимагає ретельного планування..."
         */
        categoryDescription?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        servicesList?:
          | {
              serviceName: string;
              price: string;
              /**
               * Додаткова інформація, яка буде виводитися дрібним шрифтом поруч із ціною
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            position?: ('left' | 'right') | null;
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentImage';
          }
        | {
            heading: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordion';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  fullName: string;
  phone: string;
  email: string;
  patientType: string;
  referralSource: string;
  comment?: string | null;
  locale: 'es' | 'en' | 'uk';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'pricing';
        value: number | Pricing;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonText?: T;
              buttonLink?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        advantages?:
          | T
          | {
              sectionTitle?: T;
              compactSpacing?: T;
              itemLayout?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        aboutUsGrid?:
          | T
          | {
              sectionTitle?: T;
              buttonText?: T;
              buttonLink?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    buttonText?: T;
                    buttonLink?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        philosophy?:
          | T
          | {
              sectionTitle?: T;
              compactSpacing?: T;
              itemLayout?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        promotions?:
          | T
          | {
              position?: T;
              promotion?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              position?: T;
              title?: T;
              compactSpacing?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              sectionTitle?: T;
              compactSpacing?: T;
              description?: T;
              source?: T;
              selectedMembers?: T;
              sliderLimit?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              sectionTitle?: T;
              compactSpacing?: T;
              embedCode?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        contentImage?:
          | T
          | {
              position?: T;
              title?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        pricingGroupShowcase?:
          | T
          | {
              position?: T;
              image?: T;
              pricingGroup?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              title?: T;
              compactSpacing?: T;
              content?: T;
              backgroundImage?: T;
              overlayColor?: T;
              overlayOpacity?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        globalContactSection?:
          | T
          | {
              compactSpacing?: T;
              id?: T;
              blockName?: T;
            };
        contactSection?:
          | T
          | {
              sectionTitle?: T;
              compactSpacing?: T;
              sectionDescription?: T;
              formTitle?: T;
              formDescription?: T;
              submitButtonLabel?: T;
              fullNamePlaceholder?: T;
              phonePlaceholder?: T;
              emailPlaceholder?: T;
              patientTypePlaceholder?: T;
              patientTypeOptions?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              referralSourcePlaceholder?: T;
              referralSourceOptions?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              commentPlaceholder?: T;
              successMessage?: T;
              errorMessage?: T;
              contactRowsOrder?:
                | T
                | {
                    row?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  items?:
    | T
    | {
        serviceName?: T;
        price?: T;
        pricePrefix?: T;
        note?: T;
        servicePage?: T;
        id?: T;
      };
  detailsLinkLabel?: T;
  categories?:
    | T
    | {
        categoryTitle?: T;
        categoryDescription?: T;
        servicesList?:
          | T
          | {
              serviceName?: T;
              price?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  image?: T;
  validUntil?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        contentImage?:
          | T
          | {
              position?: T;
              text?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        accordion?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  description?: T;
  photo?: T;
  photoHover?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  patientType?: T;
  referralSource?: T;
  comment?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  menuItems?:
    | {
        label: string;
        /**
         * Use /services for pages or #contact_us for anchors
         */
        link: string;
        id?: string | null;
      }[]
    | null;
  header?: {
    logo?: (number | null) | Media;
    menuButtonLabel?: string | null;
  };
  footer?: {
    logo?: (number | null) | Media;
    copyright?: string | null;
  };
  contacts?: {
    sectionTitle?: string | null;
    sectionDescription?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    phoneLabel?: string | null;
    emailLabel?: string | null;
    addressLabel?: string | null;
    transportLabel?: string | null;
    socialLabel?: string | null;
    email?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
    telegram?: string | null;
    address?: string | null;
    transport?: string | null;
    googleMapsUrl?: string | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'twitter' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  globalContactSection?: {
    sectionTitle?: string | null;
    sectionDescription?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    formTitle?: string | null;
    formDescription?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    submitButtonLabel?: string | null;
    fullNamePlaceholder?: string | null;
    phonePlaceholder?: string | null;
    emailPlaceholder?: string | null;
    patientTypePlaceholder?: string | null;
    patientTypes?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    referralSourcePlaceholder?: string | null;
    refSources?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    commentPlaceholder?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
  };
  formNotifications?: {
    /**
     * Where contact form submissions should be sent.
     */
    recipientEmail?: string | null;
    sendConfirmationToUser?: boolean | null;
    adminSubject?: string | null;
    /**
     * Use the editor for bold, italic, lists and links.
     */
    adminMessage?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    userSubject?: string | null;
    /**
     * Use the editor for bold, italic, lists and links.
     */
    userMessage?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Drag to reorder sections. Uncheck "Enabled" to hide a section.
   */
  sectionOrder?:
    | {
        section:
          | 'hero'
          | 'advantages'
          | 'aboutUs'
          | 'philosophy'
          | 'promotions'
          | 'team'
          | 'reviews'
          | 'gallery'
          | 'whyUs'
          | 'contacts';
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  hero: {
    title: string;
    subtitle?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
    image?: (number | null) | Media;
  };
  advantages?:
    | {
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  aboutUs?: {
    blocks?:
      | {
          title?: string | null;
          text: string;
          buttonText?: string | null;
          buttonLink?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  philosophy?: {
    sectionTitle?: string | null;
    cards?:
      | {
          title: string;
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  teamSection?: {
    title?: string | null;
  };
  reviews?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * Paste Google Reviews widget or other HTML embed code here
     */
    embedCode?: string | null;
  };
  gallery?: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  whyUs?: {
    title?: string | null;
    text?: string | null;
  };
  contactsSection?: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-footer".
 */
export interface HeaderFooter {
  id: number;
  menuItems?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  header?: {
    logo?: (number | null) | Media;
    menuButtonLabel?: string | null;
  };
  footer?: {
    logo?: (number | null) | Media;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contacts".
 */
export interface SiteContact {
  id: number;
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  telegram?: string | null;
  address?: string | null;
  transport?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'twitter' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: paste Google Maps embed URL for the contact section map
   */
  googleMapsUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  header?:
    | T
    | {
        logo?: T;
        menuButtonLabel?: T;
      };
  footer?:
    | T
    | {
        logo?: T;
        copyright?: T;
      };
  contacts?:
    | T
    | {
        sectionTitle?: T;
        sectionDescription?: T;
        phoneLabel?: T;
        emailLabel?: T;
        addressLabel?: T;
        transportLabel?: T;
        socialLabel?: T;
        email?: T;
        phone?: T;
        whatsapp?: T;
        telegram?: T;
        address?: T;
        transport?: T;
        googleMapsUrl?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  globalContactSection?:
    | T
    | {
        sectionTitle?: T;
        sectionDescription?: T;
        formTitle?: T;
        formDescription?: T;
        submitButtonLabel?: T;
        fullNamePlaceholder?: T;
        phonePlaceholder?: T;
        emailPlaceholder?: T;
        patientTypePlaceholder?: T;
        patientTypes?:
          | T
          | {
              label?: T;
              id?: T;
            };
        referralSourcePlaceholder?: T;
        refSources?:
          | T
          | {
              label?: T;
              id?: T;
            };
        commentPlaceholder?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  formNotifications?:
    | T
    | {
        recipientEmail?: T;
        sendConfirmationToUser?: T;
        adminSubject?: T;
        adminMessage?: T;
        userSubject?: T;
        userMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  sectionOrder?:
    | T
    | {
        section?: T;
        enabled?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonText?: T;
        buttonLink?: T;
        image?: T;
      };
  advantages?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  aboutUs?:
    | T
    | {
        blocks?:
          | T
          | {
              title?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              image?: T;
              id?: T;
            };
      };
  philosophy?:
    | T
    | {
        sectionTitle?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  teamSection?:
    | T
    | {
        title?: T;
      };
  reviews?:
    | T
    | {
        title?: T;
        subtitle?: T;
        embedCode?: T;
      };
  gallery?:
    | T
    | {
        title?: T;
        description?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  whyUs?:
    | T
    | {
        title?: T;
        text?: T;
      };
  contactsSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-footer_select".
 */
export interface HeaderFooterSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  header?:
    | T
    | {
        logo?: T;
        menuButtonLabel?: T;
      };
  footer?:
    | T
    | {
        logo?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contacts_select".
 */
export interface SiteContactsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  whatsapp?: T;
  telegram?: T;
  address?: T;
  transport?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  googleMapsUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}